on:
  pull_request:
    types: [closed]

jobs:
  sync_branch:
    if: contains(github.head_ref, 'hotfix/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            console.log(JSON.stringify(context.issue))
            github.pulls.create({
              title: `Sync for hot fix number: ${context.issue.number}`,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for hot fix !',
              head: 'master',
              base: 'develop',
              maintainer_can_modify: false
            })
