on:
  pull_request:
    types: [closed]

jobs:
  sync_branch:
    if: contains(github.head_ref, 'hotfix/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            console.log(JSON.stringify(github), 'github info come here')
            github.pulls.create({
              title: `Sync for hot fix number: ${context.issue.number}`,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `👋 Thanks for hot fix ! You can read the description [here](https://github.com/Nanxy-Tran/blog-by-vue/pull/${context.issue.number})`,
              head: 'master',
              base: 'develop',
              maintainer_can_modify: false
            })
